ARG PHP_IMAGE
ARG PHP_VERSION
FROM php:$PHP_VERSION-alpine
RUN apk update && apk add autoconf build-base bash unzip parallel colordiff sqlite
RUN apk upgrade sqlite
RUN pecl install ast-1.1.3 && docker-php-ext-enable ast
RUN curl https://getcomposer.org/download/latest-2.x/composer.phar -o /usr/bin/composer.phar && chmod a+x /usr/bin/composer.phar
WORKDIR /phan

ADD composer.json composer.lock ./
RUN composer.phar install && composer.phar clear-cache

ADD . .
