#!/home/amorrison/development/php-src/package/bin/php
<?php
declare(strict_types=1);

$time_start = microtime(true);

// Grab these before we define our own classes
$internal_class_name_list = get_declared_classes();
$internal_interface_name_list = get_declared_interfaces();
$internal_trait_name_list = get_declared_traits();
$internal_function_name_list = get_defined_functions()['internal'];

require_once(__DIR__.'/Phan/Bootstrap.php');
require_once(__DIR__.'/Phan/Deprecated/CLI.php');
require_once(__DIR__.'/Phan/Deprecated/Util.php');
require_once(__DIR__.'/Phan/Deprecated/AST.php');

use Phan\Language\File;
use Phan\CodeBase;

$code_base = new CodeBase(
    $internal_class_name_list,
    $internal_interface_name_list,
    $internal_trait_name_list,
    $internal_function_name_list
);

$cnt = count($files);

foreach($files as $i => $file) {
    $file = new File(
        $code_base,
        $file
    );
    $file->passOne();
    /*
	$ast = \ast\parse_file($file, $version = 10);
	else {
		pass1($file, '', false, $ast, 'global');
	}
     */
}

