#!/usr/bin/env php
<?php declare(strict_types=1);

// Grab these before we define our own classes
$internal_class_name_list = get_declared_classes();
$internal_interface_name_list = get_declared_interfaces();
$internal_trait_name_list = get_declared_traits();
$internal_function_name_list = get_defined_functions()['internal'];

require_once(__DIR__.'/Phan/Bootstrap.php');

use \Phan\Analyzer;
use \Phan\CodeBase;
use \Phan\Log;
use \Phan\CLI;

// \Phan\Analyzer::analyze will emit messages to STDOUT
(new Analyzer())->analyze(
    new CodeBase(
        $internal_class_name_list,
        $internal_interface_name_list,
        $internal_trait_name_list,
        $internal_function_name_list
    ),
    (new CLI)->getFileList()
);
