#!/usr/bin/env bash
function print_all_tests {
	echo "Valid tests are below:" 1>&2
	echo 1>&2
	SCRIPT_PATH="${BASH_SOURCE[0]}"
	SCRIPT_DIR="$( cd "$( dirname "$SCRIPT_PATH" )" && pwd )"
	grep --only -E '^\s*\w+\)' < $SCRIPT_PATH| sed 's,\s*\|),,g' |sort 1>&2
	grep --only -E '<testsuite name="\w+"' < "$SCRIPT_DIR/../phpunit.xml" | sed 's,.*name="\(\w\+\)".*,\1,g' | sort 1>&2
}
if [ "$#" != 1 ]; then
	echo "Usage: $0 \$TEST_SUITE" 1>&2
	print_all_tests
	exit 1
fi
TEST_SUITE="$1"
if [ "x$TEST_SUITE" == "x" ]; then
	echo "Provided TEST_SUITE param was empty" 1>&2
	exit 1
fi
case "$TEST_SUITE" in
	__FakeSelfTest)
		./phan --memory-limit 1G
		exit $?
		;;
	__FakeSelfFallbackTest)
		PLUGIN_PATH=$HOME/.phan-ci/UnusedVariablePlugin-c20aea3e.php

		ARGS=""
		if [ -e "$PLUGIN_PATH" ]; then
			ARGS="--plugin $PLUGIN_PATH"
		fi
		./phan --plugin PHPUnitNotDeadCodePlugin \
			$ARGS \
			--dead-code-detection \
			--polyfill-parse-all-element-doc-comments \
			--force-polyfill-parser \
			--memory-limit 1G
		exit $?
		;;
	__FakePHP70Test)
		# TODO: Can this use phpunit?
		cd tests/php70_test
		./test.sh
		exit $?
		;;
	__FakeRewritingTest)
		cd tests/misc/rewriting_test
		./test.sh
		exit $?
		;;
	__FakeFallbackTest)
		cd tests/misc/fallback_test
		./test.sh
		exit $?
		;;
	__FakePluginTest)
		cd tests/plugin_test
		./test.sh
		exit $?
		;;
	__FakeToolTest)
		cd tests/tool_test
		./test.sh
		exit $?
		;;
	__FakeConfigOverrideTest)
		cd tests/misc/config_override_test
		./test.sh
		exit $?
		;;
	__*)
		echo "Unknown test '$TEST_SUITE' (Tests beginning with __ are not phpunit tests)" 1>&2
		echo 1>&2
		print_all_tests
		exit 1
		;;
	-*)
		echo "This script does not accept flags" 1>&2
		echo "Usage: $0 \$TEST_SUITE" 1>&2
		echo 1>&2
		print_all_tests
		exit 1
		;;
	*)
		./vendor/bin/phpunit --colors --testsuite "$TEST_SUITE"
		exit $?
		;;
esac

