/home/amorrison/development/phan/tests/0002_dangling_var.phpt
/home/amorrison/development/phan/tests/0003_return_type.phpt
/home/amorrison/development/phan/tests/0004_number_of_args.phpt
/home/amorrison/development/phan/tests/0005_arg_types.phpt
/home/amorrison/development/phan/tests/0006_var_combo.phpt
/home/amorrison/development/phan/tests/0007_self_call.phpt
/home/amorrison/development/phan/tests/0008_parent_call.phpt
/home/amorrison/development/phan/tests/0009_method_call.phpt
/home/amorrison/development/phan/tests/0010_this_method_call.phpt
/home/amorrison/development/phan/tests/0011_internal_arg.phpt
/home/amorrison/development/phan/tests/0012_redef_interface_class.phpt
/home/amorrison/development/phan/tests/0013_alternate_signature.phpt
/home/amorrison/development/phan/tests/0014_varargs_internal.phpt
/home/amorrison/development/phan/tests/0015_variadic_call.phpt
/home/amorrison/development/phan/tests/0016_trait_call.phpt
/home/amorrison/development/phan/tests/0017_taint.phpt
/home/amorrison/development/phan/tests/0018_return_var.phpt
/home/amorrison/development/phan/tests/0019_static_var.phpt
/home/amorrison/development/phan/tests/0020_global_var.phpt
/home/amorrison/development/phan/tests/0021_foreach.phpt
/home/amorrison/development/phan/tests/0022_ref_params.phpt
/home/amorrison/development/phan/tests/0023_doc_comment.phpt
/home/amorrison/development/phan/tests/0024_GLOBALS.phpt
/home/amorrison/development/phan/tests/0025_catch.phpt
/home/amorrison/development/phan/tests/0026_closure.phpt
/home/amorrison/development/phan/tests/0027_void.phpt
/home/amorrison/development/phan/tests/0028_construct.phpt
/home/amorrison/development/phan/tests/0029_internal_method.phpt
/home/amorrison/development/phan/tests/0030_def_arg_type.phpt
/home/amorrison/development/phan/tests/0031_prop.phpt
/home/amorrison/development/phan/tests/0032_ns_alias.phpt
/home/amorrison/development/phan/tests/0033_ns_function.phpt
/home/amorrison/development/phan/tests/0034_generics.phpt
/home/amorrison/development/phan/tests/0035_class_const.phpt
/home/amorrison/development/phan/tests/0036_properties.phpt
/home/amorrison/development/phan/tests/0037_properties2.phpt
/home/amorrison/development/phan/tests/0038_properties3.phpt
/home/amorrison/development/phan/tests/0039_static_property_ref.phpt
/home/amorrison/development/phan/tests/0040_deprecated.phpt
/home/amorrison/development/phan/tests/0041_array_comp.phpt
/home/amorrison/development/phan/tests/0042_array_access.phpt
/home/amorrison/development/phan/tests/0043_array_access_object.phpt
