#!/usr/bin/env php
<?php declare(strict_types = 1);

require_once(__DIR__ . '/../../src/requirements.php');

$code_base = require_once(__DIR__ . '/../../src/codebase.php');
require_once(__DIR__ . '/../../src/Phan/Bootstrap.php');

use Phan\CLI;
use Phan\CodeBase;
use Phan\Config;
use Phan\Issue;
use Phan\Output\Collector\BufferingCollector;
use Phan\Output\Filter\CategoryIssueFilter;
use Phan\Output\Filter\ChainedIssueFilter;
use Phan\Output\Filter\FileIssueFilter;
use Phan\Output\ParallelConsoleOutput;
use Phan\Output\PrinterFactory;
use Symfony\Component\Console\Output\ConsoleOutput;
use Phan\Phan;

// Create our CLI interface and load arguments
$cli = new CLI();

// Enable PHP5 -> PHP7 checks
Config::get()->backward_compatibility_checks = true;

// Re-analyze all files
Config::get()->reanalyze_file_list = true;

// Obtain the config
$codeclimate_config = json_decode(file_get_contents('/config.json'), true);

$include_paths = [];

// Todo: wrap with `-l` console logic instead of custom function
$queue_with_include_paths = function ($dir_path) use ($include_paths, &$queue_with_include_paths) {
    foreach (scandir($dir_path) as $f) {
        if ($f !== '.' and $f !== '..') {
            if (is_dir("$dir_path/$f")) {
                $queue_with_include_paths("$dir_path/$f");
            } else {
                $include_paths[] = "$dir_path/$f";
            }
        }
    }
};

foreach ($codeclimate_config['include_paths'] as $path) {
    if (is_dir('/code/' . $path)) {
        $queue_with_include_paths('/code/' . $path);
    } else {
        $include_paths[] = "/code/$path";
    }
}

$output = new ConsoleOutput();
$factory = new PrinterFactory();
$printer = $factory->getPrinter('codeclimate', $output);
Phan::setPrinter($printer);

$filter = new ChainedIssueFilter([
    new FileIssueFilter(new Phan()),
    new CategoryIssueFilter(-1 ^ Issue::CATEGORY_UNDEFINED)
]);
$collector = new BufferingCollector($filter);
Phan::setIssueCollector($collector);

// Analyze the file list provided via the CLI
Phan::analyzeFileList($code_base, $include_paths);
