#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PHPCBF="$DIR/PHP_CodeSniffer/vendor/bin/phpcbf"
set -xu
if [[ "$#" != 0 ]]; then
	echo "Executing phpcbf --standard=ruleset.xml $@"  1>&2
	php -d memory_limit=2G "$PHPCBF" --standard=phpcs.xml "$@"
else
	# Automatically detect PSR-2 and PSR-12 syntax issues in Phan itself
	php -d memory_limit=2G "$PHPCBF" --standard=phpcs.xml tests/Phan src internal/lib internal/*.php .phan tool/make_stubs phan_client
fi
