#!/usr/bin/env bash
# This has been tested with phpcs.phar 3.3.0 (3.3.0 or newer is required)
set -xu
# Automatically detect PSR-2 and PSR-12 syntax issues in Phan itself
if [[ "$#" != 0 ]]; then
	echo "Executing phpcs.phar --standard=ruleset.xml $@"  1>&2
	phpcs.phar --standard=ruleset.xml "$@"
else
	# Automatically fix PSR-2 syntax issues in Phan itself
	phpcs.phar --standard=ruleset.xml tests/Phan src .phan tool phan_client
fi
