#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PHAN_DIR="$(dirname "$DIR")"
STANDARD="$PHAN_DIR/phpcs.xml"
PHPCBF="$DIR/PHP_CodeSniffer/vendor/bin/phpcbf"
set -xu
if [[ "$#" != 0 ]]; then
	echo "Executing phpcbf --standard="$STANDARD" $@"  1>&2
	php -d memory_limit=2G "$PHPCBF" --standard="$STANDARD" "$@"
else
	# Automatically detect PSR-2 and PSR-12 syntax issues in Phan itself
	php -d memory_limit=2G "$PHPCBF" --standard="$STANDARD" tests/Phan src internal/lib internal/*.php .phan tool/make_stubs phan_client
fi
