#!/usr/bin/env bash
# This has been tested with phpcbf.phar 3.3.0 (3.3.0 or newer is required)
set -eu
if [[ "$#" != 0 ]]; then
	echo "Executing phpcbf.phar --standard=ruleset.xml $@"  1>&2
	phpcbf.phar --standard=ruleset.xml "$@"
else
	# Automatically fix PSR-2 and PSR-12 syntax issues in Phan itself
	phpcbf.phar --standard=ruleset.xml tests/Phan src internal .phan tool/make_stubs phan_client
fi
